import { LESSONS } from './data.js';
import { CORE_LESSON_META, REPAIR_LESSONS, RECOMMENDATION_WEIGHTS } from './adaptive-data.js';
import { VOCABULARY_ITEMS, VOCAB_REVIEW_RATINGS } from './learning-extension-data.js';

const CORE_KEY='ielts-self-learning-v1', ADAPTIVE_KEY='ielts-adaptive-v1', DAY=86400000;
let queued=false, applying=false;
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const label=s=>({reading:'Reading',listening:'Listening',writing:'Writing',speaking:'Speaking',vocabulary:'Vocabulary',grammar:'Grammar','learning-better':'Learning Better'})[s]||s;

function eligibleVocab(core,a){const done=new Set(core.completedLessons||[]), repairs=new Set(Object.entries(a.repairProgress||{}).filter(([,v])=>v?.completed).map(([k])=>k));return VOCABULARY_ITEMS.filter(x=>done.has(x.sourceLesson)||repairs.has(x.sourceLesson));}
function ensure(core,a=read(ADAPTIVE_KEY)){a.reviewSchedule||={};a.repairProgress||={};a.reviewHistory||=[];a.vocabularySchedule||={};a.vocabularyHistory||=[];a.skillPerformance||={};a.learningHistory||=[];for(const x of eligibleVocab(core,a))a.vocabularySchedule[x.id]||={dueAt:Date.now(),intervalDays:0,attempts:0,lastRating:null,selected:null,checked:false,lastCorrect:null};return a;}
function save(a){const next=JSON.stringify(a);if(localStorage.getItem(ADAPTIVE_KEY)!==next)localStorage.setItem(ADAPTIVE_KEY,next);}

function qmap(){const m=new Map();for(const l of LESSONS)for(const s of l.sections||[])for(const b of s.blocks||[])if(b.type==='quiz')m.set(b.id,{l,b});return m;}
const QUIZZES=qmap();
function updatePerformance(core,a){const stats={};const add=(s,c)=>{stats[s]||={answered:0,correct:0};stats[s].answered++;if(c)stats[s].correct++};for(const[id,v]of Object.entries(core.lessonAnswers||{})){if(!v?.checked)continue;const f=QUIZZES.get(id);if(f)add(f.l.skill,v.selected===f.b.answer);}for(const l of REPAIR_LESSONS){const ans=a.repairProgress?.[l.id]?.answers||{};l.questions.forEach((q,i)=>{const v=ans[i];if(v?.checked)add(l.skill,v.selected===q.answer)});}for(const[s,v]of Object.entries(stats))a.skillPerformance[s]={...v,accuracy:v.correct/v.answered,confidence:v.answered>=8?'Moderate':v.answered>=4?'Emerging':'Low',updatedAt:Date.now()};}
function baseWeak(core,s){const p=core.profile?.placementSections||{};if(['reading','listening','vocabulary','grammar'].includes(s))return p[s]==null?.45:(6-p[s])/6;if(s==='writing'){const g=p.grammar==null?.45:(6-p.grammar)/6,v=p.vocabulary==null?.45:(6-p.vocabulary)/6;return Math.max(g,v)*.85+.15}if(s==='speaking')return .55;return .35;}
function weakness(core,a,s){const b=baseWeak(core,s),p=a.skillPerformance?.[s];if(!p?.answered)return b;const w=p.answered>=8?.65:p.answered>=4?.45:.25;return b*(1-w)+(1-p.accuracy)*w;}
function dueErrors(core,a){const now=Date.now();return(core.errors||[]).filter(e=>(a.reviewSchedule?.[e.id]?.dueAt??e.ts??now)<=now);}
function dueVocab(core,a){const now=Date.now(),ok=new Set(eligibleVocab(core,a).map(x=>x.id));return VOCABULARY_ITEMS.filter(x=>ok.has(x.id)&&(a.vocabularySchedule?.[x.id]?.dueAt||0)<=now);}
function counts(core,a){const since=Date.now()-7*DAY,out={reading:0,listening:0,writing:0,speaking:0,vocabulary:0,grammar:0,'learning-better':0},by=new Map([...CORE_LESSON_META,...REPAIR_LESSONS].map(x=>[x.id,x.skill]));for(const r of core.studyHistory||[]){if((r.ts||0)<since)continue;const s=by.get(r.lessonId);if(s&&out[s]!=null)out[s]++;}for(const r of a.learningHistory||[]){if((r.ts||0)>=since&&r.skill&&out[r.skill]!=null)out[r.skill]++;}return out;}
function candidates(){return[...CORE_LESSON_META,...REPAIR_LESSONS.map(x=>({...x,targetRelevance:x.skill==='grammar'?.8:.75}))];}
function score(core,a,l){const c=counts(core,a),w=RECOMMENDATION_WEIGHTS,weak=weakness(core,a,l.skill),due=Math.min(1,dueErrors(core,a).filter(x=>x.skill===l.skill).length/2),bal=(c[l.skill]||0)>=2?0:(c[l.skill]||0)===1?.55:1,dif=Math.max(0,1-Math.abs(Number(core.profile?.recommendedDifficulty||3)-l.difficulty)/3),mins=Number(core.study?.preferredMinutes||20),tm=l.estimatedMinutes<=mins?1:Math.max(.15,mins/l.estimatedMinutes),recent=[...(core.studyHistory||[]),...(a.learningHistory||[])].slice(-6).some(x=>x.lessonId===l.id),b={weakness:weak*w.weakness,dueReview:due*w.dueReview,targetRelevance:l.targetRelevance*w.targetRelevance,skillBalance:bal*w.skillBalance,difficultyMatch:dif*w.difficultyMatch,timeMatch:tm*w.timeMatch,recentPenalty:recent?w.recentRepetitionPenalty:0};return{l,b,score:b.weakness+b.dueReview+b.targetRelevance+b.skillBalance+b.difficultyMatch+b.timeMatch-b.recentPenalty};}

function setHTML(root,html,key){if(!root||root.dataset.extFingerprint===key)return;root.dataset.extFingerprint=key;root.innerHTML=html;}
function today(core,a){const root=document.querySelector('[data-adaptive-root="today"]');if(!root)return;if(!core.placement){root.hidden=true;return}root.hidden=false;const ed=dueErrors(core,a),vd=dueVocab(core,a);if(ed.length||vd.length){const key=`review-${ed.length}-${vd.length}`;return setHTML(root,`<div class="adaptive-top"><div><div class="eyebrow">Adaptive Today · retrieval first</div><h2>${ed.length+vd.length} review item${ed.length+vd.length===1?'':'s'} due</h2></div><span class="chip warning">Spaced review</span></div><p class="muted">${ed.length} saved error${ed.length===1?'':'s'} · ${vd.length} vocabulary item${vd.length===1?'':'s'}. Due retrieval comes before new material.</p><div class="cluster"><button class="btn primary" data-nav="improve">Open Review Queue</button><span class="small muted">≈ ${Math.min(12,Math.max(3,(ed.length+vd.length)*2))} min</span></div>`,key);}const r=candidates().map(x=>score(core,a,x)).sort((x,y)=>y.score-x.score)[0],b=r.b,key=`lesson-${r.l.id}-${Math.round(r.score)}-${JSON.stringify(a.skillPerformance)}`;setHTML(root,`<div class="adaptive-top"><div><div class="eyebrow">Adaptive Today · placement + real performance</div><h2>${esc(r.l.title)}</h2></div><span class="score-badge">${Math.round(r.score)}</span></div><p class="muted">Placement starts the profile. Checked lesson answers receive more weight as evidence accumulates.</p><div class="adaptive-breakdown"><span>Weakness ${Math.round(b.weakness)}</span><span>Review ${Math.round(b.dueReview)}</span><span>Target ${Math.round(b.targetRelevance)}</span><span>Balance ${Math.round(b.skillBalance)}</span><span>Difficulty ${Math.round(b.difficultyMatch)}</span><span>Time ${Math.round(b.timeMatch)}</span>${b.recentPenalty?`<span class="penalty">Recent −${Math.round(b.recentPenalty)}</span>`:''}</div><div class="cluster"><button class="btn primary" data-lesson="${r.l.id}">Start recommended lesson</button><span class="small muted">${r.l.estimatedMinutes} min · ${label(r.l.skill)} · Difficulty ${r.l.difficulty}/5</span></div>`,key);}

function vcard(x,s){const opts=[x.answer,...x.distractors];return`<article class="vocab-card"><div class="cluster"><span class="chip">${x.sourceLesson}</span><span class="small muted">${esc(x.meaning)}</span></div><strong>${esc(x.prompt)}</strong><div class="options">${opts.map((o,i)=>`<button class="option ${s.checked?(o===x.answer?'correct':o===s.selected?'wrong':''):(o===s.selected?'selected':'')}" data-lx="vopt" data-id="${x.id}" data-value="${esc(o)}" ${s.checked?'disabled':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div><button class="btn small-btn ${s.checked?'soft':'primary'}" data-lx="vcheck" data-id="${x.id}" ${!s.selected||s.checked?'disabled':''}>${s.checked?'Checked':'Check'}</button>${s.checked?`<div class="feedback ${s.lastCorrect?'correct':'wrong'}"><strong>${s.lastCorrect?'Correct':'Review the chunk'}</strong><br>${esc(x.term)} · ${esc(x.collocations.join(' · '))}</div><div class="rating-row"><span class="small muted">Next review:</span>${Object.entries(VOCAB_REVIEW_RATINGS).map(([k,r])=>`<button class="btn ghost small-btn" data-lx="vrate" data-id="${x.id}" data-rating="${k}">${r.label}</button>`).join('')}</div>`:''}</article>`;}
function vocab(core,a){if(!location.hash.includes('/improve')||document.querySelector('[data-lx-root="vocab"]'))return;const anchor=document.querySelector('[data-adaptive-root="repair"]')||document.querySelector('[data-adaptive-root="review"]');if(!anchor)return;const ok=eligibleVocab(core,a),now=Date.now(),due=ok.filter(x=>(a.vocabularySchedule[x.id]?.dueAt||0)<=now),later=ok.filter(x=>(a.vocabularySchedule[x.id]?.dueAt||0)>now);anchor.insertAdjacentHTML('afterend',`<section class="card extension-card" data-lx-root="vocab"><div class="adaptive-top"><div><div class="eyebrow">Vocabulary Review</div><h2>${due.length?`${due.length} due now`:ok.length?'Vocabulary is scheduled':'Build vocabulary from lessons'}</h2></div><span class="chip primary">Context → recall → reuse</span></div><p class="muted">Cards unlock from completed lessons. Review phrases and collocations in context.</p>${due.length?`<div class="vocab-stack">${due.slice(0,5).map(x=>vcard(x,a.vocabularySchedule[x.id])).join('')}</div>`:ok.length?'<div class="empty-state"><strong>No vocabulary is due.</strong><p>Return when the next interval is ready.</p></div>':'<div class="empty-state"><strong>No cards unlocked yet.</strong><p>Complete R01, L01, W01, or VG01 to seed lesson-based vocabulary review.</p></div>'}${later.length?`<details class="scheduled-reviews"><summary>${later.length} scheduled later</summary>${later.slice(0,8).map(x=>`<div class="scheduled-row"><span>${esc(x.term)}</span><span class="small muted">${new Date(a.vocabularySchedule[x.id].dueAt).toLocaleDateString()}</span></div>`).join('')}</details>`:''}</section>`);}
function performance(core,a){if(!location.hash.includes('/progress')||document.querySelector('[data-lx-root="performance"]'))return;const cards=document.querySelectorAll('#main .card');const anchor=[...cards].find(x=>x.textContent.includes('Section profile'));if(!anchor)return;const rows=['reading','listening','writing','speaking','vocabulary','grammar'].map(s=>{const p=a.skillPerformance[s],bw=baseWeak(core,s),cw=weakness(core,a,s),pct=p?.answered?Math.round(p.accuracy*100):Math.round((1-bw)*100);return`<div class="profile-row lx-profile"><strong>${label(s)}</strong><div class="meter"><span style="width:${pct}%"></span></div><span>${p?.answered?`${p.correct}/${p.answered}`:'placement'}</span><span class="small muted">priority ${Math.round(cw*100)}</span></div>`}).join('');anchor.insertAdjacentHTML('afterend',`<section class="card extension-card" data-lx-root="performance" style="margin-top:18px"><div class="eyebrow">Observed learning profile</div><h2 style="margin:8px 0 14px">Real answers now update the profile.</h2><p class="muted">Placement remains the starting signal. As checked answers accumulate, actual performance gets progressively more weight.</p>${rows}</section>`);}

function rq(l,q,i,s={}){return`<div class="quiz-card"><div class="q-title">${esc(q.prompt)}</div><div class="options">${q.options.map((o,n)=>`<button class="option ${s.checked?(o===q.answer?'correct':o===s.selected?'wrong':''):(o===s.selected?'selected':'')}" data-lx="ropt" data-rid="${l.id}" data-q="${i}" data-value="${esc(o)}" ${s.checked?'disabled':''}><span class="option-letter">${String.fromCharCode(65+n)}</span><span>${esc(o)}</span></button>`).join('')}</div><button class="btn small-btn ${s.checked?'soft':'primary'}" data-lx="rcheck" data-rid="${l.id}" data-q="${i}" ${!s.selected||s.checked?'disabled':''}>${s.checked?'Checked':'Check'}</button>${s.checked?`<div class="feedback ${s.selected===q.answer?'correct':'wrong'}"><strong>${s.selected===q.answer?'Correct':'Not yet'}</strong><br>${esc(q.rationale)}</div>`:''}</div>`;}
function repairRoute(core,a){const m=location.hash.match(/^#\/lesson\/(VG0[1-3])$/),main=document.querySelector('#main');if(!m||!main)return;const l=REPAIR_LESSONS.find(x=>x.id===m[1]);if(!l||main.dataset.lxLesson===l.id)return;const p=a.repairProgress[l.id]||{answers:{}};main.dataset.lxLesson=l.id;main.innerHTML=`<article class="lesson-shell extension-lesson"><div class="lesson-top"><button class="btn ghost small-btn" data-nav="improve">← Improve</button><div class="eyebrow" style="margin-top:20px">${label(l.skill)} · Repair</div><h1 class="lesson-title">${esc(l.title)}</h1><div class="meta"><span>${l.cefr}</span><span>${l.estimatedMinutes} min</span><span>Difficulty ${l.difficulty}/5</span>${p.completed?'<span class="chip success">Completed</span>':''}</div><p class="lede">${esc(l.objective)}</p></div><section class="lesson-section"><h2>1. Learn</h2>${l.learn.map(x=>`<p>${esc(x)}</p>`).join('')}<div class="callout"><strong>Notice these patterns</strong><br>${l.examples.map(esc).join(' · ')}</div></section><section class="lesson-section"><h2>2. Guided Practice</h2>${l.questions.map((q,i)=>rq(l,q,i,p.answers?.[i])).join('')}</section><section class="lesson-section"><h2>3. Review and reuse</h2><p>Explain the rule in your own words, then produce one new example.</p><textarea class="text-area" data-lx-note="${l.id}" placeholder="My own example...">${esc(p.note||'')}</textarea></section><section class="lesson-section"><div class="cluster" style="justify-content:space-between"><div><div class="eyebrow">Finish</div><h2 style="margin-top:6px">Repair → retry → review</h2></div><button class="btn primary" data-lx="rcomplete" data-rid="${l.id}">${p.completed?'Completed ✓':'Mark repair complete'}</button></div></section></article>`;}

function apply(){if(applying)return;applying=true;try{const core=read(CORE_KEY),a=ensure(core);updatePerformance(core,a);save(a);today(core,a);vocab(core,a);performance(core,a);repairRoute(core,a);}finally{applying=false}}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}
function click(e){const old=e.target.closest('[data-adaptive-action="open-repair"]');if(old){e.preventDefault();e.stopImmediatePropagation();location.hash=`#/lesson/${old.dataset.repairId}`;return}const t=e.target.closest('[data-lx]');if(!t)return;const core=read(CORE_KEY),a=ensure(core),act=t.dataset.lx;if(act==='vopt'){const s=a.vocabularySchedule[t.dataset.id];if(!s.checked)s.selected=t.dataset.value}if(act==='vcheck'){const x=VOCABULARY_ITEMS.find(v=>v.id===t.dataset.id),s=a.vocabularySchedule[x.id];if(s.selected){s.checked=true;s.lastCorrect=s.selected===x.answer}}if(act==='vrate'){const s=a.vocabularySchedule[t.dataset.id],r=VOCAB_REVIEW_RATINGS[t.dataset.rating],days=Math.max(r.minDays,Math.round((s.intervalDays||1)*r.multiplier));Object.assign(s,{intervalDays:days,dueAt:Date.now()+days*DAY,attempts:(s.attempts||0)+1,lastRating:t.dataset.rating,selected:null,checked:false});a.vocabularyHistory.push({ts:Date.now(),id:t.dataset.id,rating:t.dataset.rating,nextDays:days})}if(act==='ropt'){const id=t.dataset.rid,i=Number(t.dataset.q);a.repairProgress[id]||={answers:{}};a.repairProgress[id].answers||={};a.repairProgress[id].answers[i]={selected:t.dataset.value,checked:false}}if(act==='rcheck'){const s=a.repairProgress?.[t.dataset.rid]?.answers?.[Number(t.dataset.q)];if(s?.selected)s.checked=true}if(act==='rcomplete'){const id=t.dataset.rid,l=REPAIR_LESSONS.find(x=>x.id===id);a.repairProgress[id]||={answers:{}};a.repairProgress[id].completed=true;a.repairProgress[id].completedAt=Date.now();a.learningHistory.push({ts:Date.now(),type:'repair-complete',lessonId:id,skill:l?.skill})}save(a);queue();}
function input(e){const n=e.target.closest('[data-lx-note]');if(!n)return;const core=read(CORE_KEY),a=ensure(core),id=n.dataset.lxNote;a.repairProgress[id]||={answers:{}};a.repairProgress[id].note=n.value;save(a);}

document.addEventListener('click',click,true);document.addEventListener('input',input);window.addEventListener('hashchange',queue);window.addEventListener('ielts-adaptive-state-change',queue);
const observer=new MutationObserver(()=>{if(!applying)queue()});observer.observe(document.querySelector('#app'),{childList:true,subtree:true});queue();
